### ISSUE TITLE
kaplan meier

### ISSUE THREAD

**Issue by mehak25** [ZhiGroup/pytorch_ehr#18]
I attended your session during ACM-BCB conference. Great presentation!
I have one question regarding survival analysis.
What is the purpose of the "kaplan meier plot" used in survival analysis in ModelTraining file. Is it some kind of baseline to your actual models or is it shoing that survival probability predicted by best model is same as kaplan meier ?

**Comment by lrasmy** [comment]
Thanks Mehak, I also liked your presentation on data imputation using Bi-GANs

Coming to the Kaplan–Meier (KM) curves, Yes, it is mainly showing the stratified survival analysis for patients according to their predicted survival score over time in days since admission. In a way that perfect separations between lines (stratifying patients in different risk groups) show the good discrimination of our trained survival predictive model.

Hopefully that answers your question

Thank you,
Laila

**Comment by mehak25** [comment]
Thanks, Laila for clarifying it.
I am trying to apply models like DeepHit and was looking for visualizations to explain the results.
Kaplan-Meier seems a good idea.

Thanks,
Mehak
