### ISSUE TITLE
Getting embedding error when running main.py with toy.train

### ISSUE THREAD

**Issue by agr505** [ZhiGroup/pytorch_ehr#20]
Hi @ZhiGroup and @lrasmy,

I am very impressed by this work.

I am getting the attached error when trying to retrieve the embeddings in the EmbedPatients_MB(self,mb_t, mtd) method when using the toy.train file.  I just wanted to test the repo's code with this sample data. Should I not use this file and just follow the ACM-BCB-Tutorial instead to generate the processed data?

Thank you so much for providing this code and these tutorials, it is very help.

Best Regards,

Aaron Reich

![pytorch ehr error](https://user-images.githubusercontent.com/13120394/197365679-6f18eee6-6b5a-46fb-a4b4-75a94535c81f.png)

**Comment by lrasmy** [comment]
Hi Aaron,

Thank you for your interest in our Repo and the supporting feedback.

Yes please, follow some of the provided tutorials either the ACM-BCB or the MIMIC IV one. The Toy files are just to share the format of the input data, you can also follow our preprocessing code on your data in order to get the same.

Please let us know if you face any other issues.

Thank you,
Laila
